"""LOOPS.md — the open-loop ledger (the brain's task system).

One markdown file, one loop per line, in a strict grammar that `brain loop`
manages and `brain loop lint` enforces. Humans can read it in any editor;
sessions never hand-edit it — they call the CLI so the format cannot drift.

    - [ ] L-003 · Lock fourth fall seat · due 2026-09-09 · owner alvin · area harvard
          · prio 1 · since 2026-08-31 · touched 2026-09-01 · next: click "Enroll Selected"

Fields (fixed order, ` · ` separated, `next:` always last so it may contain
anything except the separator):

    id       L-NNN, assigned by `brain loop add`, never reused
    title    short noun phrase
    due      YYYY-MM-DD — a hard deadline, or the date to act/review by
    owner    alvin | claude | waiting:<who>   (who the ball is with)
    area     harvard | jobs | training | business | life | brain | other
    prio     1 (drop everything) | 2 (this week) | 3 (when convenient)
    since    date the loop was opened
    touched  date of the last edit — staleness is measured from here
    next     the single concrete next action
    done     (closed loops only) date closed

The "🔥 Hot right now" section of NOW.md is a rendered VIEW of this file
between `<!-- loops:start -->` / `<!-- loops:end -->` markers — regenerated by
`brain loop render` (which every write runs) and checked by lint. Rendering is
deterministic and date-free so NOW.md only changes when a loop changes;
`brain today` is the time-aware view (countdowns, overdue, aging waits).
"""
from __future__ import annotations

import hashlib
import json
import re
import subprocess
from dataclasses import dataclass, field, replace
from datetime import date, datetime
from pathlib import Path

SEP = " · "
LOOPS_FILE = "LOOPS.md"
INBOX_FILE = "LOOPS-INBOX.md"
INBOX_SEEN_FILE = ".loops-inbox-seen.jsonl"
NOW_FILE = "NOW.md"
START_MARK = "<!-- loops:start -->"
END_MARK = "<!-- loops:end -->"

AREAS = ("harvard", "jobs", "training", "business", "life", "brain", "other")
OWNER_RE = re.compile(r"^(alvin|claude|waiting:[a-z0-9][a-z0-9-]*)$")
ID_RE = re.compile(r"^L-\d{3,}$")
LINE_RE = re.compile(r"^- \[( |x)\] (L-\d{3,})" + re.escape(SEP) + r"(.*)$")
DATE_FMT = "%Y-%m-%d"
FIELD_KEYS = ("due", "owner", "area", "prio", "since", "touched", "next", "done", "note")

STALE_DAYS = 7          # lint warns when an open loop hasn't been touched this long
WAITING_NAG_DAYS = 5    # lint warns when a waiting-for is older than this

HEADER = """# LOOPS — open loops
<!-- Managed by `brain loop` (add / done / edit / list / lint / render). Do NOT hand-edit lines.
     Grammar: - [ ] L-NNN · title · due YYYY-MM-DD · owner alvin|claude|waiting:<who> · area <area>
              · prio 1-3 · since YYYY-MM-DD · touched YYYY-MM-DD · next: <one concrete action>
     Areas: harvard jobs training business life brain other. `due` = hard deadline or act/review-by date.
     NOW.md's hot section is rendered from the Open list — never edit that block by hand. -->
"""


class LoopError(ValueError):
    """A malformed loop, an unknown id, or an invalid field value."""


@dataclass
class Loop:
    id: str
    title: str
    due: date
    owner: str
    area: str
    next: str
    prio: int = 2
    since: date | None = None
    touched: date | None = None
    done: date | None = None
    note: str = ""

    @property
    def closed(self) -> bool:
        return self.done is not None

    @property
    def waiting_on(self) -> str:
        return self.owner[len("waiting:"):] if self.owner.startswith("waiting:") else ""

    def to_line(self) -> str:
        parts = [self.title,
                 f"due {self.due.isoformat()}",
                 f"owner {self.owner}",
                 f"area {self.area}",
                 f"prio {self.prio}",
                 f"since {(self.since or self.due).isoformat()}",
                 f"touched {(self.touched or self.since or self.due).isoformat()}"]
        if self.done:
            parts.append(f"done {self.done.isoformat()}")
        if self.note:
            parts.append(f"note {self.note}")
        parts.append(f"next: {self.next}")
        box = "x" if self.closed else " "
        return f"- [{box}] {self.id}{SEP}{SEP.join(parts)}"


# ── parsing ───────────────────────────────────────────────────────────────────

def _parse_date(s: str, what: str) -> date:
    try:
        return datetime.strptime(s.strip(), DATE_FMT).date()
    except ValueError:
        raise LoopError(f"{what}: bad date {s!r} (want YYYY-MM-DD)")


def parse_line(line: str) -> Loop:
    """Parse one loop line; raises LoopError with a precise reason."""
    m = LINE_RE.match(line.rstrip())
    if not m:
        raise LoopError(f"unparseable line: {line.strip()[:80]!r}")
    box, lid, rest = m.groups()
    pieces = rest.split(SEP)
    title = pieces[0].strip()
    if not title:
        raise LoopError(f"{lid}: empty title")
    fields: dict[str, str] = {}
    i = 1
    while i < len(pieces):
        piece = pieces[i]
        key, _, val = piece.partition(" ")
        key = key.rstrip(":")
        if key == "next":
            # `next` is always last: everything after it belongs to the action text
            fields["next"] = SEP.join([val] + pieces[i + 1:]).strip()
            break
        if key not in FIELD_KEYS:
            raise LoopError(f"{lid}: unknown field {key!r}")
        fields[key] = val.strip()
        i += 1
    for req in ("due", "owner", "area", "next"):
        if not fields.get(req):
            raise LoopError(f"{lid}: missing {req}")
    loop = Loop(
        id=lid, title=title,
        due=_parse_date(fields["due"], f"{lid} due"),
        owner=fields["owner"], area=fields["area"], next=fields["next"],
        prio=int(fields.get("prio", "2")) if fields.get("prio", "2").isdigit() else -1,
        since=_parse_date(fields["since"], f"{lid} since") if fields.get("since") else None,
        touched=_parse_date(fields["touched"], f"{lid} touched") if fields.get("touched") else None,
        done=_parse_date(fields["done"], f"{lid} done") if fields.get("done") else None,
        note=fields.get("note", ""),
    )
    if (box == "x") != loop.closed:
        raise LoopError(f"{lid}: checkbox and `done` disagree")
    validate(loop)
    return loop


def validate(loop: Loop):
    if not ID_RE.match(loop.id):
        raise LoopError(f"bad id {loop.id!r}")
    if not OWNER_RE.match(loop.owner):
        raise LoopError(f"{loop.id}: bad owner {loop.owner!r} (alvin | claude | waiting:<who>)")
    if loop.area not in AREAS:
        raise LoopError(f"{loop.id}: bad area {loop.area!r} (one of {', '.join(AREAS)})")
    if loop.prio not in (1, 2, 3):
        raise LoopError(f"{loop.id}: bad prio {loop.prio!r} (1, 2 or 3)")
    for name, text in (("title", loop.title), ("next", loop.next), ("note", loop.note)):
        if "·" in text or "\n" in text:
            raise LoopError(f"{loop.id}: {name} may not contain '·' or newlines")
    if not loop.next.strip():
        raise LoopError(f"{loop.id}: next action is empty")


@dataclass
class Ledger:
    open: list[Loop] = field(default_factory=list)
    closed: list[Loop] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)   # parse errors, line-numbered

    def all(self) -> list[Loop]:
        return self.open + self.closed

    def get(self, lid: str) -> Loop:
        for l in self.all():
            if l.id == lid:
                return l
        raise LoopError(f"no such loop {lid}")

    def next_id(self) -> str:
        n = max((int(l.id.split("-")[1]) for l in self.all()), default=0)
        return f"L-{n + 1:03d}"


def parse(text: str) -> Ledger:
    """Parse LOOPS.md. Lines outside `## Open` / `## Closed` are ignored;
    malformed loop lines are collected in `errors` (never silently dropped)."""
    ledger = Ledger()
    section = None
    for no, raw in enumerate(text.splitlines(), 1):
        line = raw.rstrip()
        low = line.lower()
        if low.startswith("## open"):
            section = "open"
            continue
        if low.startswith("## closed"):
            section = "closed"
            continue
        if section is None or not line.startswith("- ["):
            continue
        try:
            loop = parse_line(line)
        except LoopError as e:
            ledger.errors.append(f"line {no}: {e}")
            continue
        if section == "open" and loop.closed:
            ledger.errors.append(f"line {no}: {loop.id} is closed but listed under Open")
        elif section == "closed" and not loop.closed:
            ledger.errors.append(f"line {no}: {loop.id} is open but listed under Closed")
        (ledger.closed if section == "closed" else ledger.open).append(loop)
    return ledger


def serialize(ledger: Ledger, keep_closed: int = 40) -> str:
    """Deterministic file body: open loops by (prio, due, id), closed newest first."""
    open_ = sorted(ledger.open, key=lambda l: (l.prio, l.due, l.id))
    closed = sorted(ledger.closed, key=lambda l: (l.done, l.id), reverse=True)[:keep_closed]
    out = [HEADER.rstrip(), "", "## Open", ""]
    out += [l.to_line() for l in open_] or ["(none)"]
    out += ["", "## Closed", ""]
    out += [l.to_line() for l in closed] or ["(none)"]
    return "\n".join(out) + "\n"


# ── file I/O ──────────────────────────────────────────────────────────────────

def loops_path(root: Path) -> Path:
    return Path(root) / LOOPS_FILE


def load(root: Path) -> Ledger:
    p = loops_path(root)
    return parse(p.read_text(encoding="utf-8")) if p.is_file() else Ledger()


def save(root: Path, ledger: Ledger):
    if ledger.errors:
        raise LoopError("refusing to rewrite LOOPS.md while it has parse errors:\n  "
                        + "\n  ".join(ledger.errors))
    loops_path(root).write_text(serialize(ledger), encoding="utf-8")


def _guarded_root(root: Path) -> bool:
    """True if committing here is allowed. A test process (unittest imported) must
    never commit the REAL vault — in Sep 2026 a test run left eight commits in it."""
    import sys
    from brain import DATA_DIR
    if "unittest" in sys.modules:
        try:
            if Path(root).resolve() == (DATA_DIR / "vault").resolve():
                return False
        except OSError:
            return False
    return True


def git_commit(root: Path, message: str) -> bool:
    """Commit the vault if it is a git repo and something changed. Never raises."""
    root = Path(root)
    if not (root / ".git").exists() or not _guarded_root(root):
        return False
    try:
        subprocess.run(["git", "-C", str(root), "add", "-A"], check=True,
                       capture_output=True, timeout=30)
        r = subprocess.run(["git", "-C", str(root), "commit", "-q", "-m", message],
                           capture_output=True, timeout=30)
        return r.returncode == 0
    except (subprocess.SubprocessError, OSError):
        return False


def git_commit_paths(root: Path, paths: list[str], message: str) -> bool:
    """Commit only these vault-relative paths (files or directories), leaving any
    other dirt — a half-edited curated file, someone else's staged change — alone.
    Used for writes that happen inside a larger operation (extractor ingest,
    inbox triage) so machine-generated churn gets its own commit. Never raises."""
    root = Path(root)
    if not (root / ".git").exists() or not _guarded_root(root):
        return False
    present = [p for p in paths if (root / p).exists()]  # a missing pathspec is fatal to git
    if not present:
        return False
    try:
        subprocess.run(["git", "-C", str(root), "add", "-A", "--"] + present,
                       check=True, capture_output=True, timeout=30)
        r = subprocess.run(["git", "-C", str(root), "commit", "-q", "-m", message, "--"] + present,
                           capture_output=True, timeout=30)
        return r.returncode == 0
    except (subprocess.SubprocessError, OSError):
        return False


# ── operations (each writes LOOPS.md, re-renders NOW.md, commits) ─────────────

def refresh_now(root: Path, ledger: Ledger | None = None) -> bool:
    """Re-render NOW.md: the whole file when it is generated (`brain now`),
    else only the legacy marked block."""
    from brain import now  # lazy: now.py imports this module
    if now.is_generated(root):
        return now.write(root)
    return render_now(root, ledger)


def _finish(root: Path, ledger: Ledger, message: str, commit: bool = True):
    save(root, ledger)
    refresh_now(root, ledger)
    if commit:
        git_commit(root, message)


def add(root: Path, title: str, due: str, owner: str, area: str, next_: str,
        prio: int = 2, since: str | None = None, today: date | None = None,
        commit: bool = True) -> Loop:
    today = today or date.today()
    ledger = load(root)
    if ledger.errors:
        raise LoopError("LOOPS.md has parse errors — run `brain loop lint`")
    loop = Loop(id=ledger.next_id(), title=title.strip(), due=_parse_date(due, "due"),
                owner=owner.strip(), area=area.strip(), next=next_.strip(), prio=int(prio),
                since=_parse_date(since, "since") if since else today, touched=today)
    validate(loop)
    ledger.open.append(loop)
    _finish(root, ledger, f"loop {loop.id}: open — {loop.title}", commit)
    return loop


def done(root: Path, lid: str, note: str = "", today: date | None = None,
         commit: bool = True) -> Loop:
    today = today or date.today()
    ledger = load(root)
    loop = ledger.get(lid)
    if loop.closed:
        raise LoopError(f"{lid} is already closed ({loop.done})")
    ledger.open.remove(loop)
    closed = replace(loop, done=today, touched=today, note=note.strip() or loop.note)
    validate(closed)
    ledger.closed.append(closed)
    _finish(root, ledger, f"loop {lid}: done — {loop.title}", commit)
    return closed


def edit(root: Path, lid: str, today: date | None = None, commit: bool = True,
         **changes) -> Loop:
    """Update any of title/due/owner/area/prio/next/note on an open loop."""
    today = today or date.today()
    ledger = load(root)
    loop = ledger.get(lid)
    if loop.closed:
        raise LoopError(f"{lid} is closed — reopen by adding a new loop")
    clean = {}
    for k, v in changes.items():
        if v is None:
            continue
        if k == "due":
            v = _parse_date(v, f"{lid} due")
        elif k == "prio":
            v = int(v)
        elif k == "next_":
            k = "next"
        clean[k] = v
    if not clean:
        raise LoopError("nothing to change")
    updated = replace(loop, touched=today, **clean)
    validate(updated)
    ledger.open[ledger.open.index(loop)] = updated
    _finish(root, ledger, f"loop {lid}: edit {', '.join(clean)}", commit)
    return updated


def touch(root: Path, lid: str, today: date | None = None, commit: bool = True) -> Loop:
    return edit(root, lid, today=today, commit=commit, touched=today or date.today())


# ── NOW.md view ───────────────────────────────────────────────────────────────

def _fmt_due(d: date) -> str:
    return d.strftime("%b %d").replace(" 0", " ")


def render_block(ledger: Ledger) -> str:
    """The hot-section body: date-free, so it only changes when loops change."""
    open_ = sorted(ledger.open, key=lambda l: (l.prio, l.due, l.id))
    lines = []
    active = [l for l in open_ if not l.waiting_on]
    waiting = [l for l in open_ if l.waiting_on]
    for l in active:
        who = "" if l.owner == "alvin" else f" · {l.owner}"
        lines.append(f"- **{l.title}** — due {_fmt_due(l.due)} · P{l.prio}{who} · next: {l.next}  `{l.id}`")
    if waiting:
        lines.append("- ⏳ **Waiting on:** " + "; ".join(
            f"{l.waiting_on} — {l.title} (by {_fmt_due(l.due)}) `{l.id}`" for l in waiting))
    if not lines:
        lines.append("- (no open loops — `brain loop add` to open one)")
    return "\n".join(lines)


def render_now(root: Path, ledger: Ledger | None = None) -> bool:
    """Rewrite the marked block in NOW.md from the ledger. Returns True if changed.
    NOW.md without markers is left untouched (lint reports it)."""
    ledger = ledger or load(root)
    p = Path(root) / NOW_FILE
    if not p.is_file():
        return False
    text = p.read_text(encoding="utf-8")
    if START_MARK not in text or END_MARK not in text:
        return False
    head, _, tail = text.partition(START_MARK)
    _, _, tail = tail.partition(END_MARK)
    new = f"{head}{START_MARK}\n{render_block(ledger)}\n{END_MARK}{tail}"
    if new != text:
        p.write_text(new, encoding="utf-8")
        return True
    return False


def now_block_stale(root: Path, ledger: Ledger) -> str:
    """'' if NOW.md's block matches the ledger, else a reason."""
    p = Path(root) / NOW_FILE
    if not p.is_file():
        return "NOW.md missing"
    text = p.read_text(encoding="utf-8")
    if START_MARK not in text or END_MARK not in text:
        return f"NOW.md has no {START_MARK} / {END_MARK} markers"
    current = text.split(START_MARK, 1)[1].split(END_MARK, 1)[0].strip("\n")
    return "" if current == render_block(ledger) else "NOW.md hot section is out of date — run `brain loop render`"


# ── lint ──────────────────────────────────────────────────────────────────────

def lint(root: Path, today: date | None = None) -> tuple[list[str], list[str]]:
    """(errors, warnings). Errors mean the ledger is not trustworthy."""
    today = today or date.today()
    ledger = load(root)
    errors = list(ledger.errors)
    warnings: list[str] = []
    if not loops_path(root).is_file():
        return [f"{LOOPS_FILE} missing"], []
    seen: dict[str, int] = {}
    for l in ledger.all():
        seen[l.id] = seen.get(l.id, 0) + 1
    errors += [f"duplicate id {i}" for i, n in seen.items() if n > 1]
    from brain import now
    stale = now.stale(root) if now.is_generated(root) else now_block_stale(root, ledger)
    if stale:
        errors.append(stale)
    for l in ledger.open:
        age = (today - (l.touched or l.since or today)).days
        if l.due < today:
            warnings.append(f"{l.id} overdue by {(today - l.due).days}d: {l.title}")
        if age > STALE_DAYS:
            warnings.append(f"{l.id} untouched for {age}d: {l.title}")
        if l.waiting_on and age > WAITING_NAG_DAYS:
            warnings.append(f"{l.id} waiting on {l.waiting_on} for {age}d — nudge")
    return errors, warnings


# ── search (for brain ask / brain_context) ────────────────────────────────────

def search(root: Path, query: str, limit: int = 5, include_closed: bool = False) -> list[Loop]:
    """Loops whose title/next/note share keywords with the query, best first (open before closed)."""
    from brain.decisions import _tokens
    q = _tokens(query)
    if not q:
        return []
    ledger = load(root)
    scored = []
    for l in ledger.open + (ledger.closed if include_closed else []):
        hit = len(q & _tokens(" ".join([l.title, l.next, l.note, l.area])))
        if hit:
            scored.append((hit, 0 if not l.closed else 1, l))
    scored.sort(key=lambda x: (-x[0], x[1], x[2].id))
    return [l for _, _, l in scored[:limit]]


# ── today ─────────────────────────────────────────────────────────────────────

def _rel(d: date, today: date) -> str:
    n = (d - today).days
    if n < 0:
        return f"OVERDUE {-n}d"
    if n == 0:
        return "TODAY"
    return f"{n}d"


def today_report(root: Path, today: date | None = None, horizon: int = 7,
                 doctor_line: str = "", decisions: list[str] | None = None) -> str:
    """Deterministic action card for a session start (no LLM, no clock except `today`)."""
    today = today or date.today()
    ledger = load(root)
    open_ = sorted(ledger.open, key=lambda l: (l.due, l.prio, l.id))
    out = [f"⏰ {today.strftime('%a %Y-%m-%d')} — brain action card"]
    if doctor_line:
        out.append(doctor_line)
    if ledger.errors:
        out.append(f"✗ LOOPS.md has {len(ledger.errors)} parse error(s) — run `brain loop lint`")
    due = [l for l in open_ if (l.due - today).days <= horizon]
    out.append(f"\nDUE (overdue → next {horizon}d):" if due else f"\nDUE: nothing in the next {horizon} days")
    for l in due:
        out.append(f"  {l.due.strftime('%b %d')} {_rel(l.due, today):>10}  {l.id} P{l.prio} {l.title} → {l.next}")
    waiting = [l for l in open_ if l.waiting_on]
    if waiting:
        out.append("\nWAITING ON:")
        for l in waiting:
            age = (today - (l.touched or l.since or today)).days
            nag = "  ← nudge" if age > WAITING_NAG_DAYS else ""
            out.append(f"  {l.waiting_on} {age}d  {l.id} {l.title} (by {l.due.strftime('%b %d')}){nag}")
    mine = [l for l in open_ if l.owner == "claude"]
    if mine:
        out.append("\nCLAUDE CAN DO NOW:")
        for l in mine:
            out.append(f"  {l.id} {l.title} → {l.next}")
    top = sorted((l for l in open_ if not l.waiting_on), key=lambda l: (l.prio, l.due, l.id))[:3]
    if top:
        out.append("\nTOP 3 NEXT ACTIONS:")
        for i, l in enumerate(top, 1):
            out.append(f"  {i}. {l.next}  ({l.id}, due {l.due.strftime('%b %d')})")
    if decisions:
        out.append("\nRECENT DECISIONS:")
        out += [f"  {d}" for d in decisions]
    inbox = inbox_list(root)
    if inbox:
        out.append(f"\nINBOX: {len(inbox)} untriaged action item(s) from the extractor — `brain loop inbox` to triage")
    later = len(open_) - len(due)
    out.append(f"\n{len(open_)} open loop(s), {later} beyond the horizon · `brain loop list` for all")
    return "\n".join(out)


def brief(root: Path, today: date | None = None, limit: int = 200) -> str:
    """One plain-text line for a phone push: the most urgent loops with countdowns."""
    today = today or date.today()
    ledger = load(root)
    open_ = sorted((l for l in ledger.open if not l.waiting_on), key=lambda l: (l.due, l.prio, l.id))
    parts = []
    for l in open_:
        n = (l.due - today).days
        when = "today" if n == 0 else (f"overdue {-n}d" if n < 0 else f"{n}d")
        parts.append(f"{l.title} ({when}): {l.next}")
    text = ""
    for p in parts:
        cand = (text + " · " if text else "") + p
        if len(cand) > limit:
            break
        text = cand
    return text or "No open loops."


# ── inbox: action items the extractor found, awaiting triage into real loops ──

INBOX_HEADER = """# LOOPS-INBOX — untriaged action items
<!-- Written by the brain's extractor (brain add / brain_remember / session capture) whenever
     remembered text contains an open action item. These are NOT loops yet: triage each with
     `brain loop add "<title>" --due ... --next ... --from-inbox N` or discard with
     `brain loop inbox --drop N`. The nightly sync empties this file.
     Triage is remembered (.loops-inbox-seen.jsonl): a dropped or triaged item is never
     re-added by the extractor, however many times a session re-states it. -->
"""
INBOX_LINE_RE = re.compile(r"^- (\d{4}-\d{2}-\d{2}) · (.+?)(?: · from: (.*))?$")


def inbox_path(root: Path) -> Path:
    return Path(root) / INBOX_FILE


def inbox_seen_path(root: Path) -> Path:
    return Path(root) / INBOX_SEEN_FILE


def inbox_list(root: Path) -> list[dict]:
    """[{date, text, source}] in file order (1-based index = position + 1)."""
    p = inbox_path(root)
    if not p.is_file():
        return []
    out = []
    for line in p.read_text(encoding="utf-8").splitlines():
        m = INBOX_LINE_RE.match(line.rstrip())
        if m:
            out.append({"date": m.group(1), "text": m.group(2).strip(), "source": (m.group(3) or "").strip()})
    return out


def _inbox_write(root: Path, items: list[dict]):
    body = INBOX_HEADER + "\n" + "".join(
        f"- {i['date']} · {i['text']}" + (f" · from: {i['source']}" if i["source"] else "") + "\n"
        for i in items)
    inbox_path(root).write_text(body, encoding="utf-8")


def _inbox_key(text: str) -> str:
    """Hash of the normalized task text, the identity used to suppress re-adds.
    Case, whitespace, and trailing punctuation don't count as differences — the
    extractor restates the same sentence with exactly that kind of drift."""
    norm = " ".join(str(text).split()).replace("·", "-").lower().rstrip(".!?,;: ")
    return hashlib.sha256(norm.encode("utf-8")).hexdigest()[:16]


def inbox_seen(root: Path) -> set[str]:
    """Hashes of every task ever dropped or triaged out of the inbox."""
    p = inbox_seen_path(root)
    if not p.is_file():
        return set()
    seen = set()
    for line in p.read_text(encoding="utf-8").splitlines():
        try:
            h = json.loads(line).get("hash")
        except (json.JSONDecodeError, AttributeError):
            continue
        if h:
            seen.add(h)
    return seen


def _inbox_seen_add(root: Path, items: list[dict], action: str, today: date | None = None):
    """Append triage records to the seen ledger (JSONL, append-only, machine-written)."""
    if not items:
        return
    today = today or date.today()
    with open(inbox_seen_path(root), "a", encoding="utf-8") as f:
        for i in items:
            f.write(json.dumps({"hash": _inbox_key(i["text"]), "text": i["text"],
                                "source": i.get("source", ""), "date": today.isoformat(),
                                "action": action}, ensure_ascii=False) + "\n")


def inbox_add(root: Path, texts: list[str], source: str = "", today: date | None = None) -> int:
    """Append candidate tasks, deduped against what is already waiting AND against
    everything previously dropped or triaged (the seen ledger) — the extractor
    re-mining a transcript must not resurface an item the user already dispatched.
    Returns how many were added."""
    root = Path(root)
    if not root.is_dir():
        return 0
    today = today or date.today()
    items = inbox_list(root)
    have = {_inbox_key(i["text"]) for i in items} | inbox_seen(root)
    added = 0
    for t in texts:
        t = " ".join(str(t).split()).replace("·", "-").strip()
        if not t or _inbox_key(t) in have:
            continue
        items.append({"date": today.isoformat(), "text": t, "source": " ".join(source.split()).replace("·", "-")})
        have.add(_inbox_key(t))
        added += 1
    if added:
        _inbox_write(root, items)
    return added


def inbox_drop(root: Path, index: int, action: str = "dropped", commit: bool = True) -> dict:
    """Remove one entry by 1-based index and remember it in the seen ledger so the
    extractor never re-adds it; returns it. `action` records why it left the inbox
    ("dropped" | "triaged"). LoopError if out of range."""
    items = inbox_list(root)
    if not 1 <= index <= len(items):
        raise LoopError(f"inbox has {len(items)} item(s); no item {index}")
    gone = items.pop(index - 1)
    _inbox_seen_add(root, [gone], action)
    _inbox_write(root, items)
    if commit:
        git_commit_paths(root, [INBOX_FILE, INBOX_SEEN_FILE],
                         f"loop inbox: {action} — {gone['text'][:60]}")
    return gone


def inbox_clear(root: Path, commit: bool = True) -> int:
    items = inbox_list(root)
    if items:
        _inbox_seen_add(root, items, "dropped")
        _inbox_write(root, [])
        if commit:
            git_commit_paths(root, [INBOX_FILE, INBOX_SEEN_FILE],
                             f"loop inbox: cleared {len(items)} item(s)")
    return len(items)
