"""NOW.md — the fully generated "what is going on" view.

Every AI session gets three things at start, each answering one question:

    brain today   → what to do now       (time-sorted: countdowns, waits, next actions)
    NOW.md        → what is going on     (this file: state, grouped by life area)
    CLAUDE.md     → how to behave        (rules; lives outside the vault)

NOW.md is never hand-edited. `brain now render` composes it from files that each
have exactly one writer:

    IDENTITY.md        one curated paragraph: who Alvin is right now
    LOOPS.md           open loops (title/due/owner only here — actions live in `brain today`)
    areas/<area>.md    front-matter `area:` `updated:` `aliases:` + a `## Now` block (≤4 lines)
    people/<name>.md   front-matter `name:` `role:` `updated:`
    apps/<app>.md      front-matter `name:` `purpose:` `url:` `type:` `updated:`

Rendering is deterministic (dates come from front-matter, never from the clock),
so NOW.md changes only when a source changes and lint can prove it is current.
`lint` also catches the failure mode this design exists for: an area whose
`updated:` is older than a log entry that mentions it — the fact moved, the
area's `## Now` block did not.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path

from brain import loops

NOW_FILE = loops.NOW_FILE
IDENTITY_FILE = "IDENTITY.md"
GEN_MARK = "<!-- now:generated"
MAX_NOW_LINES = 4
AREA_ORDER = list(loops.AREAS)
FM_RE = re.compile(r"\A---\n(.*?)\n---\n?", re.S)
LOG_NAME_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})\.md$")

HEADER = """# NOW — Alvin's current state
<!-- now:generated by `brain now render` from IDENTITY.md · LOOPS.md · areas/*.md (## Now) · people/*.md · apps/*.md.
     NEVER hand-edit this file — change the source file and re-render (loop / decide / area commands re-render it).
     brain today = what to do now (time-sorted) · NOW.md = what is going on (by area) · CLAUDE.md = how to behave. -->
"""

FOOTER = ("Details: `areas/` `apps/` `projects/` `people/` · decisions: `DECISIONS.md` (cite D-nnn) · "
          "what happened: `log/YYYY-MM-DD.md` · untriaged: `brain loop inbox` · health: `brain doctor`.")


class NowError(ValueError):
    pass


# ── front-matter (a deliberately tiny YAML subset: `key: value`, `key: [a, b]`) ──

def parse_frontmatter(text: str) -> tuple[dict, str]:
    m = FM_RE.match(text)
    if not m:
        return {}, text
    fm: dict = {}
    for line in m.group(1).splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        key, sep, val = line.partition(":")
        if not sep:
            raise NowError(f"bad front-matter line {line!r}")
        val = val.strip()
        if val.startswith("[") and val.endswith("]"):
            fm[key.strip()] = [v.strip().strip("'\"") for v in val[1:-1].split(",") if v.strip()]
        else:
            fm[key.strip()] = val.strip("'\"")
    return fm, text[m.end():]


def dump_frontmatter(fm: dict) -> str:
    out = ["---"]
    for k, v in fm.items():
        out.append(f"{k}: [{', '.join(v)}]" if isinstance(v, list) else f"{k}: {v}")
    out.append("---")
    return "\n".join(out) + "\n"


def _date(s, what: str) -> date:
    try:
        return datetime.strptime(str(s).strip(), "%Y-%m-%d").date()
    except (ValueError, TypeError):
        raise NowError(f"{what}: bad or missing date {s!r} (want YYYY-MM-DD)")


def _title(body: str, fallback: str) -> str:
    for line in body.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return fallback


def now_block(body: str) -> list[str]:
    """Lines of the `## Now` section (until the next heading), blank lines dropped."""
    lines, on = [], False
    for line in body.splitlines():
        if line.lower().strip() == "## now":
            on = True
            continue
        if on and (line.startswith("## ") or line.startswith("# ")):
            break
        if on and line.strip():
            lines.append(line.rstrip())
    return lines


def _fmt(d: date) -> str:
    return d.strftime("%b %d").replace(" 0", " ")


# ── sources ───────────────────────────────────────────────────────────────────

@dataclass
class Source:
    path: Path
    fm: dict
    body: str
    problems: list[str] = field(default_factory=list)


def _load_dir(root: Path, sub: str) -> list[Source]:
    d = Path(root) / sub
    if not d.is_dir():
        return []
    out = []
    for p in sorted(d.glob("*.md")):
        if p.name.upper() == "README.MD":
            continue
        try:
            fm, body = parse_frontmatter(p.read_text(encoding="utf-8"))
            out.append(Source(p, fm, body))
        except NowError as e:
            out.append(Source(p, {}, "", [str(e)]))
    return out


def log_mentions_after(root: Path, aliases: list[str], since: date) -> list[str]:
    """Log files dated after `since` that mention any alias (whole word, case-insensitive)."""
    logs = Path(root) / "log"
    if not logs.is_dir() or not aliases:
        return []
    pats = [re.compile(r"(?<![\w-])" + re.escape(a.lower()) + r"(?![\w-])") for a in aliases if a]
    hits = []
    for p in sorted(logs.glob("*.md")):
        m = LOG_NAME_RE.match(p.name)
        if not m:
            continue
        if _date(m.group(1), p.name) <= since:
            continue
        text = p.read_text(encoding="utf-8", errors="replace").lower()
        if any(pat.search(text) for pat in pats):
            hits.append(p.name)
    return hits


# ── render ────────────────────────────────────────────────────────────────────

def render_text(root: Path) -> str:
    root = Path(root)
    out = [HEADER.rstrip(), ""]

    ident = root / IDENTITY_FILE
    if ident.is_file():
        _, body = parse_frontmatter(ident.read_text(encoding="utf-8"))
        out += [body.strip(), ""]

    # open loops, grouped by area — title/due/owner/prio only; next actions live in `brain today`
    ledger = loops.load(root)
    out.append("## 🔥 Open loops — by area (what to do: `brain today`; ledger: LOOPS.md)")
    by_area: dict[str, list] = {}
    waiting = []
    for l in sorted(ledger.open, key=lambda l: (l.prio, l.due, l.id)):
        (waiting if l.waiting_on else by_area.setdefault(l.area, [])).append(l)
    for area in AREA_ORDER:
        ls = by_area.get(area)
        if not ls:
            continue
        items = "; ".join(f"{l.id} {l.title} — {_fmt(l.due)} P{l.prio}" + (" · claude" if l.owner == "claude" else "")
                          for l in ls)
        out.append(f"- **{area}:** {items}")
    if waiting:
        out.append("- ⏳ **waiting on:** " + "; ".join(
            f"{l.waiting_on} — {l.title} (by {_fmt(l.due)}, {l.id})" for l in waiting))
    if not ledger.open:
        out.append("- (no open loops)")
    out.append("")

    # areas: ## Now blocks
    areas = _load_dir(root, "areas")
    keyed = {}
    for s in areas:
        k = s.fm.get("area")
        if k:
            keyed.setdefault(k, s)
    out.append("## 📍 Now, by area")
    for key in AREA_ORDER + sorted(k for k in keyed if k not in AREA_ORDER):
        s = keyed.get(key)
        if not s:
            continue
        upd = s.fm.get("updated", "")
        try:
            upd_s = _fmt(_date(upd, s.path.name))
        except NowError:
            upd_s = "updated ?"
        else:
            upd_s = f"updated {upd_s}"
        out.append(f"### {_title(s.body, key)} · {upd_s}")
        block = now_block(s.body)
        out += block[:MAX_NOW_LINES] if block else [f"- (no `## Now` block in areas/{s.path.name})"]
    out.append("")

    # people
    people = _load_dir(root, "people")
    if people:
        waits = {}
        for l in waiting:
            waits.setdefault(l.waiting_on, []).append(l.id)
        bits = []
        for s in people:
            name = s.fm.get("name") or _title(s.body, s.path.stem)
            role = s.fm.get("role", "")
            key = s.fm.get("person", s.path.stem)
            tag = f" (⏳ {', '.join(waits[key])})" if key in waits else ""
            bits.append(f"**{name}** — {role}{tag}" if role else f"**{name}**{tag}")
        out += ["## 👥 People (files: people/)", "- " + " · ".join(bits), ""]

    # apps
    apps = _load_dir(root, "apps")
    if apps:
        out.append("## 📱 Apps (update artifacts via the Artifact tool + url; log every change in apps/<app>.md)")
        for s in apps:
            name = s.fm.get("name") or _title(s.body, s.path.stem)
            purpose = s.fm.get("purpose", "")
            url = s.fm.get("url", "")
            kind = s.fm.get("type", "artifact")
            upd = s.fm.get("updated", "")
            try:
                upd_s = f" · updated {_fmt(_date(upd, s.path.name))}"
            except NowError:
                upd_s = ""
            where = url if url else f"{kind} (no url)"
            out.append(f"- **{name}** — {purpose} — {where}{upd_s}".replace(" —  —", " —"))
        out.append("")

    out.append(FOOTER)
    return "\n".join(out) + "\n"


def is_generated(root: Path) -> bool:
    p = Path(root) / NOW_FILE
    return p.is_file() and GEN_MARK in p.read_text(encoding="utf-8")[:600]


def write(root: Path) -> bool:
    """(Re)generate NOW.md. Returns True if the file changed."""
    p = Path(root) / NOW_FILE
    new = render_text(root)
    if p.is_file() and p.read_text(encoding="utf-8") == new:
        return False
    p.write_text(new, encoding="utf-8")
    return True


def stale(root: Path) -> str:
    p = Path(root) / NOW_FILE
    if not p.is_file():
        return "NOW.md missing — run `brain now render`"
    if not is_generated(root):
        return "NOW.md is hand-written, not generated — run `brain now render` (it replaces the file)"
    return "" if p.read_text(encoding="utf-8") == render_text(root) else \
        "NOW.md is out of date with its sources — run `brain now render`"


# ── lint ──────────────────────────────────────────────────────────────────────

def lint(root: Path, today: date | None = None) -> tuple[list[str], list[str]]:
    root = Path(root)
    today = today or date.today()
    errors, warnings = [], []
    if not (root / IDENTITY_FILE).is_file():
        warnings.append(f"{IDENTITY_FILE} missing — NOW.md has no identity paragraph")
    seen: dict[str, str] = {}
    for s in _load_dir(root, "areas"):
        rel = f"areas/{s.path.name}"
        if s.problems:
            errors += [f"{rel}: {p}" for p in s.problems]
            continue
        key = s.fm.get("area")
        if not key:
            errors.append(f"{rel}: front-matter needs `area: <key>` (one of {', '.join(AREA_ORDER)})")
            continue
        if key not in AREA_ORDER:
            errors.append(f"{rel}: unknown area {key!r}")
        if key in seen:
            errors.append(f"{rel}: duplicate area {key!r} (also {seen[key]})")
        seen[key] = rel
        try:
            upd = _date(s.fm.get("updated"), rel)
        except NowError as e:
            errors.append(str(e))
            continue
        block = now_block(s.body)
        if not block:
            warnings.append(f"{rel}: no `## Now` block")
        elif len(block) > MAX_NOW_LINES:
            warnings.append(f"{rel}: `## Now` has {len(block)} lines (max {MAX_NOW_LINES}; only the first {MAX_NOW_LINES} render)")
        aliases = list(s.fm.get("aliases", [])) + [key]
        hits = log_mentions_after(root, aliases, upd)
        if hits:
            warnings.append(f"{rel}: updated {upd} but {', '.join(hits)} mention(s) it — refresh `## Now` and `brain area touch {key}`")
    for s in _load_dir(root, "apps"):
        rel = f"apps/{s.path.name}"
        if s.problems:
            errors += [f"{rel}: {p}" for p in s.problems]
        elif not s.fm.get("name"):
            warnings.append(f"{rel}: no front-matter (`name:`, `purpose:`, `url:`, `type:`, `updated:`)")
        elif not s.fm.get("url") and s.fm.get("type", "artifact") == "artifact":
            warnings.append(f"{rel}: artifact without `url:`")
    for s in _load_dir(root, "people"):
        if s.problems:
            errors += [f"people/{s.path.name}: {p}" for p in s.problems]
        elif not s.fm.get("role"):
            warnings.append(f"people/{s.path.name}: no `role:` in front-matter")
    st = stale(root)
    if st:
        errors.append(st)
    return errors, warnings


# ── area touch ────────────────────────────────────────────────────────────────

def area_file(root: Path, key: str) -> Path:
    for s in _load_dir(root, "areas"):
        if s.fm.get("area") == key:
            return s.path
    raise NowError(f"no areas/*.md has `area: {key}`")


def touch_area(root: Path, key: str, when: date | None = None) -> Path:
    """Set `updated:` on an area file (call after editing its `## Now` block) and re-render NOW.md."""
    when = when or date.today()
    p = area_file(root, key)
    fm, body = parse_frontmatter(p.read_text(encoding="utf-8"))
    fm["updated"] = when.isoformat()
    p.write_text(dump_frontmatter(fm) + body, encoding="utf-8")
    write(root)
    return p
