"""Render the graph into a human-readable markdown vault (the "g-brain" pattern).

The vault is the brain's file layer: a folder of markdown that agents and humans
can read, grep, and version with git. It holds two kinds of files:

  - curated files (NOW.md, areas/, apps/, ...) written by the person or their
    AI sessions — this module NEVER touches those;
  - generated views (DIGEST.md + graph/*.md) rendered from the knowledge graph —
    overwritten on every render, one file per top-level life-area category.

Rendering is deterministic (no LLM, no timestamps — git history carries time),
so it is fully testable offline and produces stable diffs.
"""
from pathlib import Path
from brain import DATA_DIR, config, db, graph

GENERATED_NOTE = "<!-- generated by `brain vault` — do not edit, regenerated on every add -->"


def vault_dir() -> Path:
    """The vault location (see config.vault_dir)."""
    return config.vault_dir()


def slugify(name: str) -> str:
    out = "".join(c if c.isalnum() else "-" for c in name.lower())
    while "--" in out:
        out = out.replace("--", "-")
    return out.strip("-") or "unnamed"


def _imp(n) -> float:
    return n["importance"] if "importance" in n.keys() else 0.5


def _top_categories(conn, user: str = "") -> list:
    """Top-level life-area categories: direct children of the identity node,
    plus any parentless category (mirrors graph.category_breakdown)."""
    identity = db.get_node_by_name(conn, user) if user else None
    cats = []
    for n in db.all_nodes(conn):
        if n["type"] != "category":
            continue
        parents = [e["target_id"] for e in db.edges_for_node(conn, n["id"])
                   if e["source_id"] == n["id"] and e["relation"] == "part_of"]
        if (identity and identity["id"] in parents) or not parents:
            cats.append(n)
    return sorted(cats, key=lambda c: c["name"])


def _cross_links(conn, node_id: str) -> list[str]:
    """Non-hierarchy edges of a node as display lines, deterministic order."""
    lines = []
    for e in db.edges_for_node(conn, node_id):
        if e["relation"] == "part_of":
            continue
        other_id = e["target_id"] if e["source_id"] == node_id else e["source_id"]
        other = db.get_node(conn, other_id)
        if not other or other["archived"]:
            continue
        arrow = "→" if e["source_id"] == node_id else "←"
        lines.append(f"_{e['relation']}_ {arrow} {other['name']}")
    return sorted(lines)


def _render_subtree(conn, nid: str, kids: dict, depth: int, seen: set, out: list):
    """Append markdown bullets for a node and its part_of descendants."""
    if nid in seen:
        return
    seen.add(nid)
    n = db.get_node(conn, nid)
    if not n or n["archived"]:
        return
    pad = "  " * depth
    content = (n["content"] or "").strip()
    line = f"{pad}- **{n['name']}** [{n['type']}] imp {_imp(n):.2f}"
    if content and content.lower() != n["name"].lower():
        line += f" — {content}"
    out.append(line)
    for link in _cross_links(conn, nid):
        out.append(f"{pad}  - {link}")
    children = sorted(kids.get(nid, []),
                      key=lambda c: (-_imp(db.get_node(conn, c) or {"importance": 0}),
                                     (db.get_node(conn, c) or {"name": ""})["name"]))
    for child in children:
        _render_subtree(conn, child, kids, depth + 1, seen, out)


def render(conn, user: str = "", dest=None) -> list[Path]:
    """Write the generated views into the vault; returns the paths written.

    Also removes stale generated files in graph/ (renamed/merged categories),
    but never touches anything outside the generated set.
    """
    root = Path(dest).expanduser() if dest else vault_dir()
    gdir = root / "graph"
    gdir.mkdir(parents=True, exist_ok=True)
    written = []

    # per-category subtree files
    kids = graph.children_map(conn)
    cats = _top_categories(conn, user)
    seen_slugs: dict[str, int] = {}
    cat_entries = []  # (display name, filename, item count)
    covered: set = set()
    for cat in cats:
        slug = slugify(cat["name"])
        seen_slugs[slug] = seen_slugs.get(slug, 0) + 1
        if seen_slugs[slug] > 1:
            slug = f"{slug}-{seen_slugs[slug]}"
        out = [f"# {cat['name']}", GENERATED_NOTE, ""]
        before = len(covered)
        for link in _cross_links(conn, cat["id"]):
            out.append(f"- {link}")
        for child in sorted(kids.get(cat["id"], []),
                            key=lambda c: (db.get_node(conn, c) or {"name": ""})["name"]):
            _render_subtree(conn, child, kids, 0, covered, out)
        path = gdir / f"{slug}.md"
        path.write_text("\n".join(out) + "\n")
        written.append(path)
        cat_entries.append((cat["name"], f"{slug}.md", len(covered) - before))

    # anything active that no category subtree covered (excluding the person)
    identity = db.get_node_by_name(conn, user) if user else None
    loose = [n for n in db.all_nodes(conn)
             if n["type"] != "category" and n["id"] not in covered
             and not (identity and n["id"] == identity["id"])]
    if loose:
        out = ["# Loose ends", GENERATED_NOTE, "",
               "Active memories not yet filed under a life area — `brain reorganize` files them.", ""]
        for n in sorted(loose, key=lambda n: (-_imp(n), n["name"])):
            content = (n["content"] or "").strip()
            out.append(f"- **{n['name']}** [{n['type']}] imp {_imp(n):.2f}"
                       + (f" — {content}" if content else ""))
        path = gdir / "loose-ends.md"
        path.write_text("\n".join(out) + "\n")
        written.append(path)
        cat_entries.append(("Loose ends", "loose-ends.md", len(loose)))

    # graph index
    s = db.stats(conn)
    out = ["# Graph views", GENERATED_NOTE, "",
           f"Rendered from the knowledge graph — {s['active']} active node(s), {s['edges']} edge(s).",
           "Curated memory lives one level up (NOW.md, areas/, ...); these files mirror the graph.", ""]
    for name, fname, count in cat_entries:
        out.append(f"- [{name}]({fname}) — {count} item(s)")
    index = gdir / "README.md"
    index.write_text("\n".join(out) + "\n")
    written.append(index)

    # digest at the vault root
    d = graph.digest(conn, user, loops_root=root)
    out = ["# Digest — state of the brain", GENERATED_NOTE, ""]
    if d["top"]:
        out += ["## Top of mind"] + [f"- **{t['name']}** [{t['type']}] imp {t['importance']}"
                                     for t in d["top"]] + [""]
    if d["tasks"]:
        out += ["## Open loops (from LOOPS.md)"] + [f"- {t}" for t in d["tasks"]] + [""]
    if d["fading"]:
        out += ["## Fading soon"] + [
            f"- {f['name']} ({'soon' if f['days_left'] < 1 else '~%dd' % f['days_left']})"
            for f in d["fading"]] + [""]
    if d["areas"]:
        out += ["## By area", ", ".join(f"{n} ({c})" for n, c in d["areas"]), ""]
    digest_path = root / "DIGEST.md"
    digest_path.write_text("\n".join(out) + "\n")
    written.append(digest_path)

    # drop stale generated files (e.g. a category that was renamed or merged)
    keep = {p.name for p in written if p.parent == gdir}
    for old in gdir.glob("*.md"):
        if old.name not in keep:
            old.unlink()

    return written


def auto_render(conn, user: str = ""):
    """Best-effort vault refresh after an ingest (config `vault_auto`, default on).

    The file layer must never break the write path — failures are swallowed;
    run `brain vault` directly to see them.
    """
    if not config.load().get("vault_auto", True):
        return
    try:
        render(conn, user)
    except Exception:
        pass
